CREATE DATABASE [MyBlogDB]
GO


USE [MyBlogDB]
GO

ALTER DATABASE [MyBlogDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyBlogDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyBlogDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyBlogDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyBlogDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyBlogDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyBlogDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyBlogDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyBlogDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MyBlogDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyBlogDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyBlogDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyBlogDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyBlogDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyBlogDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyBlogDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyBlogDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyBlogDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MyBlogDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyBlogDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyBlogDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyBlogDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyBlogDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyBlogDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyBlogDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyBlogDB] SET RECOVERY FULL 
GO

ALTER DATABASE [MyBlogDB] SET  MULTI_USER 
GO

ALTER DATABASE [MyBlogDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyBlogDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyBlogDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyBlogDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MyBlogDB] SET  READ_WRITE 
GO


